<meta charset="utf-8" />
<style>
    label{
        float: left;
        width: 100px;
    }
    input{
        margin-bottom: 5px;
    }
    .error{
        color:red;
    }
</style>
<h3>Insert User</h3>
<form action="" method="post">
    <label>Full name</label>
    <input type="text" name="txtname" value="" />
    <span class="error">
        <?php echo isset($data['errorName']) ? $data['errorName'] : ""; ?>
    </span>
    <br />
    <label>Email</label>
    <input type="text" name="txtemail" value="" />
    <span class="error">
        <?php echo isset($data['errorEmail']) ? $data['errorEmail'] : ""; ?>
    </span>
    <br />
    <label>Address</label>
    <input type="text" name="txtaddress" value="" />
    <span class="error">
        <?php echo isset($data['errorAddress']) ? $data['errorAddress'] : ""; ?>
    </span>
    <br />
    <label>Phone</label>
    <input type="text" name="txtphone" value="" />
    <span class="error">
        <?php echo isset($data['errorPhone']) ? $data['errorPhone'] : ""; ?>
    </span>
    <br />
    <label>Gender</label>
    Male&nbsp;<input type="radio" name="gender" value="1"  />
    Famale&nbsp;<input type="radio" name="gender" value="2" />
    <span class="error">
        <?php echo isset($data['errorGender']) ? $data['errorGender'] : ""; ?>
    </span>
    <br />
    <label>&nbsp;</label>
    <input type="submit" name="btnok" value="getInfo" />
</form>
<?php
 // echo $_SERVER["SCRIPT_NAME"];